---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
- name: initializr-service
- name: version

outputs:
- name: release

run:
  path: initializr-service/ci/scripts/build-no-test.sh